# Generated by Django 5.2 on 2026-01-30 19:58

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LivingOptionEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("de", "de"),
                            ("fr", "fr"),
                            ("it", "it"),
                            ("en", "en"),
                        ],
                        max_length=5,
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "living_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embeddings",
                        to="core.livingoption",
                    ),
                ),
            ],
            options={"unique_together": {("living_option", "language")},},
        ),
    ]
