# Generated by Django 5.2 on 2026-02-01 13:18

import django.db.models.deletion
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_livingoptionembedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.TextField()),
                ("lang", models.CharField(default="de", max_length=5)),
                ("wheelchair_required", models.BooleanField(blank=True, null=True)),
                ("care_target", models.IntegerField(blank=True, null=True)),
                (
                    "language_filter",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "query_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=1536, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank_shown", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "living_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.livingoption",
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clicks",
                        to="core.searchevent",
                    ),
                ),
            ],
        ),
    ]
