# Generated by Django 5.2 on 2026-02-01 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_searchevent_searchclick"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank_shown", models.IntegerField()),
                ("clicked", models.BooleanField(default=False)),
                ("skipped", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impressions",
                        to="core.searchevent",
                    ),
                ),
                (
                    "living_option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.livingoption",
                    ),
                ),
            ],
            options={"unique_together": {("event", "living_option")},},
        ),
    ]
