# Generated by Django 5.2 on 2026-02-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_searchimpression"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="contact_email",
            field=models.EmailField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="provider",
            name="contact_phone",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="provider",
            name="self_registered",
            field=models.BooleanField(
                default=True, help_text="True if provider submitted their own listing"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="short_description",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Plain-language description of the provider",
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="support_level_high",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="provider",
            name="support_level_low",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="provider",
            name="support_level_medium",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="provider",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="website_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="provider",
            name="wheelchair_accessible",
            field=models.BooleanField(
                default=False, help_text="Step-free access and wheelchair-usable spaces"
            ),
        ),
        migrations.AlterField(
            model_name="provider",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="Reviewed for completeness and clarity"
            ),
        ),
    ]
