# Generated by Django 5.2 on 2026-02-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_provider_contact_email_provider_contact_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="provider",
            name="review_notes",
            field=models.TextField(
                blank=True, default="", help_text="Internal notes (not shown publicly)"
            ),
        ),
        migrations.AddField(
            model_name="provider",
            name="status",
            field=models.CharField(
                choices=[
                    ("published", "Published"),
                    ("pending", "Pending review"),
                    ("rejected", "Rejected"),
                ],
                default="published",
                max_length=16,
            ),
        ),
    ]
