# Generated by Django 5.2 on 2026-02-09 21:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_provider_review_notes_provider_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProviderMagicLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, default="", max_length=254)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("edit", "Edit listing")],
                        default="edit",
                        max_length=20,
                    ),
                ),
                (
                    "token_hash",
                    models.CharField(db_index=True, default="", max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("used_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="magic_links",
                        to="core.provider",
                    ),
                ),
            ],
        ),
    ]
