# Generated by Django 5.2 on 2026-02-13 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_providermagiclink"),
    ]

    operations = [
        migrations.AddField(
            model_name="livingoption",
            name="max_age",
            field=models.PositiveSmallIntegerField(default=120),
        ),
        migrations.AddField(
            model_name="livingoption",
            name="min_age",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
