# Generated by Django 5.2 on 2026-02-13 19:27

import pgvector.django.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_livingoption_max_age_livingoption_min_age"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="livingoptionembedding",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="loe_embedding_hnsw",
                opclasses=["vector_cosine_ops"],
            ),
        ),
    ]
