# Generated by Django 5.2 on 2026-02-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_livingoptionembedding_loe_embedding_hnsw"),
    ]

    operations = [
        migrations.AddField(
            model_name="livingoption",
            name="slug",
            field=models.SlugField(default="", max_length=255),
        ),
    ]
