# Generated by Django 5.2 on 2026-02-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_livingoption_slug"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="livingoption",
            constraint=models.UniqueConstraint(
                fields=("provider", "slug"), name="uniq_provider_slug"
            ),
        ),
    ]
